baseURL = 'https://pippinbarr.github.io/'
languageCode = 'en-us'
title = 'Pippin Barr'
theme = "pippinbarr"

[taxonomies]
  tag = 'tags'
  idea = 'ideas'
  platforms = 'platforms'
  tools = 'tools'
  year = 'year'

[menu]
  [[menu.main]]
    name = "Pippin Barr"
    url = "/"
    identifier = "home"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/me/"
    identifier = "about"
    weight = 2
  [[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 3
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 4
  [[menu.main]]
    name = "Podcast"
    url = "/audio/"
    weight = 5
  [[menu.main]]
    name = "Video"
    url = "/video/"
    weight = 6

[outputs]
  section = ["html","json"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
